// <auto-generated />
using System;
using ManageEmployee.Dal.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageEmployee.Dal.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20220808142333_initial7")]
partial class initial7
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("ManageEmployee.Entities.Branch", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDelete")
                    .HasColumnType("bit");

                b.Property<string>("ManagerName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Branchs");
            });

        modelBuilder.Entity("ManageEmployee.Entities.ChartOfAccount", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                b.Property<int>("AccGroup")
                    .HasColumnType("int");

                b.Property<decimal?>("ArisingCredit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingCreditNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingDebit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingDebitNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingForeignCredit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingForeignCreditNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingForeignDebit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingForeignDebitNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingStockQuantity")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ArisingStockQuantityNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Classification")
                    .HasColumnType("int");

                b.Property<decimal?>("ClosingCredit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("ClosingDebit")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("DisplayDelete")
                    .HasColumnType("bit");

                b.Property<bool>("DisplayInsert")
                    .HasColumnType("bit");

                b.Property<string>("Duration")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("ExchangeRate")
                    .HasColumnType("decimal(18,2)");

                b.Property<bool>("HasChild")
                    .HasColumnType("bit");

                b.Property<bool>("HasDetails")
                    .HasColumnType("bit");

                b.Property<bool>("IsForeignCurrency")
                    .HasColumnType("bit");

                b.Property<bool>("IsProtected")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("OpeningCredit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningCreditNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningDebit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningDebitNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningForeignCredit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningForeignCreditNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningForeignDebit")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningForeignDebitNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningStockQuantity")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("OpeningStockQuantityNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("ParentRef")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("StockUnit")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("StockUnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("StockUnitPriceNB")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<string>("WarehouseCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ChartOfAccounts");
            });

        modelBuilder.Entity("ManageEmployee.Entities.ChartOfAccountGroup", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ChartOfAccountGroups");
            });

        modelBuilder.Entity("ManageEmployee.Entities.ChartOfAccountGroupLink", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("CodeChartOfAccount")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CodeChartOfAccountGroup")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ChartOfAccountGroupLinks");
            });

        modelBuilder.Entity("ManageEmployee.Entities.ChartOfAcountTest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ChartOfAcountTests");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Company", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<int>("AccordingAccountingRegime")
                    .HasColumnType("int");

                b.Property<string>("Address")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("AssignPerson")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("BusinessType")
                    .HasColumnType("int");

                b.Property<double>("CharterCapital")
                    .HasColumnType("float");

                b.Property<int>("Currency")
                    .HasColumnType("int");

                b.Property<string>("DayType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DecimalRate")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DecimalUnit")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Fax")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FileLogo")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FileOfBusinessRegistrationCertificate")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MST")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MethodCalcExportPrice")
                    .HasColumnType("int");

                b.Property<int>("Money")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NameOfCEO")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NameOfChiefAccountant")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NameOfChiefSupplier")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NameOfStorekeeper")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NameOfTreasurer")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Note")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NoteOfCEO")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NoteOfChiefAccountant")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NoteOfChiefSupplier")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Quatity")
                    .HasColumnType("int");

                b.Property<DateTime>("SignDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ThousandUnit")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("UnitCost")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdateAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("UserUpdated")
                    .HasColumnType("int");

                b.Property<string>("WebsiteName")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Companies");
            });

        modelBuilder.Entity("ManageEmployee.Entities.ContractType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ContractTypes");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Department", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("isDelete")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("Departments");
            });

        modelBuilder.Entity("ManageEmployee.Entities.District", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ProvinceId")
                    .HasColumnType("int");

                b.Property<int>("SortCode")
                    .HasColumnType("int");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Districts");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Gender")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("IdentityNumber")
                    .HasColumnType("float");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nationality")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PalceOrigin")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PalceResidence")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Employees");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Major", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Note")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("isDelete")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("Majors");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Position", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("Order")
                    .HasColumnType("int");

                b.Property<bool>("isDelete")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("Positions");
            });

        modelBuilder.Entity("ManageEmployee.Entities.PositionDetail", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("PositionId")
                    .HasColumnType("int");

                b.Property<bool>("isDelete")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("PositionDetails");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Province", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("SortCode")
                    .HasColumnType("int");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Provinces");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Symbol", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Note")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.Property<DateTime>("TimeIn")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("TimeOut")
                    .HasColumnType("datetime2");

                b.Property<double>("TimeTotal")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("Symbols");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Target", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ArmyNumber")
                    .HasColumnType("int");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("DateInvoice")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("IdentityCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NameContact")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Note")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Order")
                    .HasColumnType("int");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Present")
                    .HasColumnType("int");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.Property<double>("Total")
                    .HasColumnType("float");

                b.Property<double>("UnitPrice")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("Targets");
            });

        modelBuilder.Entity("ManageEmployee.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Avatar")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Bank")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("BankAccount")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("BirthDay")
                    .HasColumnType("datetime2");

                b.Property<int?>("BranchId")
                    .HasColumnType("int");

                b.Property<string>("CertificateOther")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("ContractTypeId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreateAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("DayOff")
                    .HasColumnType("int");

                b.Property<DateTime?>("DeleteAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("DepartmentId")
                    .HasColumnType("int");

                b.Property<int?>("DistrictId")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EthnicGroup")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Facebook")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<short>("Gender")
                    .HasColumnType("smallint");

                b.Property<string>("Identify")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("IdentifyCreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("IdentifyCreatedPlace")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("IdentifyExpiredDate")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDelete")
                    .HasColumnType("bit");

                b.Property<string>("Language")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastLogin")
                    .HasColumnType("datetime2");

                b.Property<string>("LicensePlates")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Literacy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LiteracyDetail")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("MajorId")
                    .HasColumnType("int");

                b.Property<string>("Nation")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("NativeDistrictId")
                    .HasColumnType("int");

                b.Property<int?>("NativeProvinceId")
                    .HasColumnType("int");

                b.Property<int?>("NativeWardId")
                    .HasColumnType("int");

                b.Property<int?>("NoOfLeaveDate")
                    .HasColumnType("int");

                b.Property<string>("Note")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("NumberWorkdays")
                    .HasColumnType("float");

                b.Property<byte[]>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<byte[]>("PasswordSalt")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<string>("PersonalTaxCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PlaceOfPermanent")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PositionDetailId")
                    .HasColumnType("int");

                b.Property<int?>("ProvinceId")
                    .HasColumnType("int");

                b.Property<bool>("Quit")
                    .HasColumnType("bit");

                b.Property<string>("Religion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("RequestPassword")
                    .HasColumnType("bit");

                b.Property<double>("Salary")
                    .HasColumnType("float");

                b.Property<DateTime?>("SendSalaryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ShareHolderCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SocialInsuranceCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("SocialInsuranceCreated")
                    .HasColumnType("datetime2");

                b.Property<double>("SocialInsuranceSalary")
                    .HasColumnType("float");

                b.Property<bool>("Status")
                    .HasColumnType("bit");

                b.Property<int?>("SymbolId")
                    .HasColumnType("int");

                b.Property<int?>("TargetId")
                    .HasColumnType("int");

                b.Property<int>("Timekeeper")
                    .HasColumnType("int");

                b.Property<int>("UnionMember")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdateAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UserCreated")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserRoleIds")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserUpdated")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("WardId")
                    .HasColumnType("int");

                b.Property<int?>("WarehouseId")
                    .HasColumnType("int");

                b.Property<bool>("isDemobilized")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("ManageEmployee.Entities.UserRole", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("UserRoles");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Ward", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DistrictId")
                    .HasColumnType("int");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("SortCode")
                    .HasColumnType("int");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Wards");
            });

        modelBuilder.Entity("ManageEmployee.Entities.Warehouse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreateAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeleteAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDelete")
                    .HasColumnType("bit");

                b.Property<string>("ManagerName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdateAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UserCreated")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserUpdated")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Warehouses");
            });
#pragma warning restore 612, 618
    }
}
